# Generated by Django 5.2.1 on 2025-08-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sor", "0002_remove_sor_rate_per_km"),
        ("trips", "0011_merge_0002_trip_soft_delete_0010_consultantrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sor",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sor_entry",
                to="trips.trip",
            ),
        ),
    ]
