# Generated by Django 5.2.1 on 2025-08-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sor', '0004_sornotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sornotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
