# Generated by Django 5.2.1 on 2025-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sor', '0005_alter_sornotification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sor',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Describe contents of crates or sac', null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='number_of_crates',
            field=models.IntegerField(blank=True, help_text='Optional: Number of crates', null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='number_of_sac',
            field=models.IntegerField(blank=True, help_text='Optional: Number of sac', null=True),
        ),
    ]
