# Generated by Django 5.2.1 on 2025-12-12 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sor', '0006_sor_description_sor_number_of_crates_and_more'),
        ('trips', '0012_add_indexes'),
        ('vehicles', '0007_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='sor',
            index=models.Index(fields=['status'], name='sor_sor_status_a70d25_idx'),
        ),
        migrations.AddIndex(
            model_name='sor',
            index=models.Index(fields=['driver', 'status'], name='sor_sor_driver__985ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='sor',
            index=models.Index(fields=['vehicle', 'status'], name='sor_sor_vehicle_8b9fba_idx'),
        ),
        migrations.AddIndex(
            model_name='sor',
            index=models.Index(fields=['created_at'], name='sor_sor_created_1e0815_idx'),
        ),
        migrations.AddIndex(
            model_name='sor',
            index=models.Index(fields=['status', 'created_at'], name='sor_sor_status_d05c75_idx'),
        ),
    ]
