# Generated by Django 5.2.1 on 2026-04-13 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sor', '0007_alter_sor_options_sor_sor_sor_status_a70d25_idx_and_more'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sor',
            name='end_odometer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='outsourced_driver_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='outsourced_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=25, help_text='Rate per KM for outsourced vehicle', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='outsourced_vehicle_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='source_type',
            field=models.CharField(choices=[('company', 'Company Vehicle'), ('outsourced_manual', 'Outsourced Manual Entry')], default='company', max_length=30),
        ),
        migrations.AddField(
            model_name='sor',
            name='start_odometer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sor',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sor',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle'),
        ),
    ]
