# Generated by Django 5.2.1 on 2026-04-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sor', '0008_sor_end_odometer_sor_outsourced_driver_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sor',
            name='bundle_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups multiple SORs that ride on the same trip.', null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='bundle_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Order of this SOR within its bundle (1, 2, 3 ...).', null=True),
        ),
    ]
