# Generated by Django 5.2.1 on 2026-08-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sor', '0009_sor_bundle_id_sor_bundle_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sor',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the vehicle arrived/goods delivered (status → completed).', null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='When the vehicle left (status → in_progress).', null=True),
        ),
    ]
