# Generated by Django 5.2.1 on 2025-07-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('vehicles', '0005_vehicle_rate_per_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiroTrackDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airotrack_device', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('course', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('device_time', models.DateTimeField()),
                ('server_time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ignition', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='geolocation.airotrackdevice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Location histories',
                'ordering': ['-device_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=6, null=True)),
                ('course', models.DecimalField(blank=True, decimal_places=2, help_text='Direction in degrees', max_digits=6, null=True)),
                ('device_time', models.DateTimeField(help_text='Time reported by the device')),
                ('server_time', models.DateTimeField(help_text='Time received by the server')),
                ('fix_time', models.DateTimeField(blank=True, help_text='GPS fix time', null=True)),
                ('valid', models.BooleanField(default=True, help_text='Whether the GPS data is valid')),
                ('address', models.TextField(blank=True, help_text='Reverse geocoded address if available', null=True)),
                ('battery_level', models.DecimalField(blank=True, decimal_places=2, help_text='Battery level in percentage', max_digits=5, null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='Signal strength in dBm', null=True)),
                ('ignition', models.BooleanField(default=False, help_text='Whether the ignition is on')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw data from AiroTrack API', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='geolocation.airotrackdevice')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='vehicles.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='LocationLog',
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['vehicle', 'device_time'], name='geolocation_vehicle_568733_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['device', 'device_time'], name='geolocation_device__d4b157_idx'),
        ),
    ]
