# Generated by Django 5.2.1 on 2025-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_hr_employee_fields'),
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_stores',
            field=models.ManyToManyField(blank=True, help_text='Stores this user has access to (for generator users)', related_name='assigned_users', to='generators.store'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_full_access',
            field=models.BooleanField(default=False, help_text='True if user has both vehicle and generator access'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Employee (Vehicle Access)'), ('generator_user', 'Generator User')], default='driver', max_length=20),
        ),
    ]
