# Generated by Django 5.2.1 on 2025-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_assigned_stores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Employee (Vehicle Access)'), ('generator_user', 'Generator User'), ('sor_team', 'SOR Team')], default='driver', max_length=20),
        ),
    ]
