# Generated by Django 5.2.1 on 2025-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_module_permission_userrole_userpermission'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='accounts_cu_user_ty_97b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['approval_status'], name='accounts_cu_approva_74d667_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'approval_status'], name='accounts_cu_user_ty_f8e518_idx'),
        ),
    ]
