# Generated by Django 5.2.1 on 2026-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_accounts_cu_user_ty_97b0bf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Employee (Vehicle Access)'), ('personal_vehicle_staff', 'Personal Vehicle Staff'), ('generator_user', 'Generator User'), ('sor_team', 'SOR Team')], default='driver', max_length=30),
        ),
    ]
