# Generated by Django 5.2.1 on 2026-01-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_default_for_personal_vehicle_staff',
            field=models.BooleanField(default=False, help_text='Default permission for personal vehicle staff role'),
        ),
    ]
