# Generated by Django 5.2.1 on 2026-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_department_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_default_for_company_vehicle_staff',
            field=models.BooleanField(default=False, help_text='Default permission for staff with company vehicle'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Driver'), ('company_vehicle_staff', 'Staff (Company Vehicle)'), ('personal_vehicle_staff', 'Staff (Personal Vehicle)'), ('generator_user', 'Generator User'), ('sor_team', 'SOR Team')], default='driver', max_length=30),
        ),
    ]
