# Generated by Django 5.2.1 on 2026-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_permission_is_default_for_company_vehicle_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Driver'), ('company_vehicle_staff', 'Staff (Company Vehicle)'), ('personal_vehicle_staff', 'Staff (Personal Vehicle)'), ('generator_user', 'Generator User'), ('sor_team', 'SOR Team'), ('p2p_service', 'P2P Service Account')], default='driver', max_length=30),
        ),
    ]
