# Generated by Django 5.2.1 on 2026-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_type',
            field=models.CharField(choices=[('web', 'Web Only'), ('mobile', 'Mobile Only'), ('both', 'Web & Mobile')], default='both', help_text='Controls which platform(s) this user can log in from', max_length=10),
        ),
    ]
