# Generated by Django 5.2.1 on 2026-03-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_access_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Driver'), ('company_vehicle_staff', 'Staff (Company Vehicle)'), ('personal_vehicle_staff', 'Staff (Personal Vehicle)'), ('generator_user', 'Generator User'), ('sor_team', 'SOR Team'), ('sor_head', 'SOR Head'), ('p2p_service', 'P2P Service Account')], default='driver', max_length=30),
        ),
    ]
