# Generated by Django 5.2.1 on 2026-03-14 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('user_created', 'User Created'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('permission_changed', 'Permission Changed'), ('vehicle_created', 'Vehicle Created'), ('vehicle_deleted', 'Vehicle Deleted'), ('trip_started', 'Trip Started'), ('trip_ended', 'Trip Ended'), ('sor_created', 'SOR Created'), ('sor_accepted', 'SOR Accepted'), ('sor_rejected', 'SOR Rejected'), ('data_exported', 'Data Exported'), ('other', 'Other')], max_length=30)),
                ('target_model', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='accounts_au_action_11cc52_idx'), models.Index(fields=['user', 'timestamp'], name='accounts_au_user_id_d4cccd_idx')],
            },
        ),
    ]
