# Generated by Django 5.2.1 on 2026-05-12 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text="Manager this user reports to. Personal trips require this manager's approval before reimbursement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
