# Generated by Django 5.2.1 on 2026-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_default_for_sor_head',
            field=models.BooleanField(default=False, help_text='Default permission for SOR Head role'),
        ),
    ]
