# Generated by Django 4.2.23 on 2025-07-22 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_and_model', models.CharField(max_length=255)),
                ('capacity_kva', models.PositiveIntegerField(help_text='Capacity in kVA')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas'), ('other', 'Other')], default='diesel', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Generator',
                'verbose_name_plural': 'Generators',
                'ordering': ('store', 'make_and_model'),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store name or code', max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, help_text='Phone / Email', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours_run', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason_for_use', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='generators.generator')),
            ],
            options={
                'verbose_name': 'Usage Tracking',
                'verbose_name_plural': 'Usage Tracking',
                'ordering': ('-date', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField(default=django.utils.timezone.now)),
                ('service_type', models.CharField(help_text='Type of service carried out', max_length=255)),
                ('next_scheduled_maintenance', models.DateField(blank=True, null=True)),
                ('service_provider', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='generators.generator')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ('-date_of_service',),
            },
        ),
        migrations.AddField(
            model_name='generator',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='generators.store'),
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_filling', models.DateField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas'), ('other', 'Other')], default='diesel', max_length=20)),
                ('litres_filled', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_rate_per_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generator_fuel_entries', to=settings.AUTH_USER_MODEL)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='generators.generator')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='generators.store')),
            ],
            options={
                'verbose_name': 'Fuel Entry',
                'verbose_name_plural': 'Fuel Entries',
                'ordering': ('-date_of_filling',),
            },
        ),
    ]
