# Generated by Django 5.2.1 on 2025-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
        ('vehicles', '0007_add_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vehicle', 'expiry_date'], name='documents_d_vehicle_377958_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'expiry_date'], name='documents_d_documen_c6c0ff_idx'),
        ),
    ]
