# Generated by Django 5.2.1 on 2026-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_documents_d_expiry__1d702a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='issuing_authority',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
