# Generated by Django 5.2.1 on 2026-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_issuing_authority'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vehicle', 'document_type'], name='documents_d_vehicle_5709ce_idx'),
        ),
    ]
