# Generated by Django 5.2.1 on 2025-12-12 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0005_alter_accident_driver'),
        ('vehicles', '0007_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['date_time'], name='accidents_a_date_ti_729e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['vehicle', 'date_time'], name='accidents_a_vehicle_14f251_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['driver', 'date_time'], name='accidents_a_driver__b16d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['status'], name='accidents_a_status_58b5d9_idx'),
        ),
    ]
