# Generated by Django 5.2.1 on 2025-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_alter_fueltransaction_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='company_invoice_number',
            field=models.CharField(blank=True, help_text='Internal company invoice number for finance tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='station_invoice_number',
            field=models.CharField(blank=True, help_text='Invoice/receipt number from the fuel station', max_length=100, null=True),
        ),
    ]
