# Generated by Django 5.2.1 on 2025-09-03 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_fueltransaction_company_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when this entry was created in the system'),
            preserve_default=False,
        ),
    ]
