# Generated by Django 5.2.1 on 2025-12-12 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_fueltransaction_created_at'),
        ('vehicles', '0007_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['date'], name='fuel_fueltr_date_0219e8_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['vehicle', 'date'], name='fuel_fueltr_vehicle_a322dd_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['driver', 'date'], name='fuel_fueltr_driver__e0dfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['created_at'], name='fuel_fueltr_created_c8491e_idx'),
        ),
    ]
