# Generated by Django 5.2.1 on 2026-02-28 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_add_indexes'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['fuel_type', 'date'], name='fuel_fueltr_fuel_ty_7990d5_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['fuel_station', 'date'], name='fuel_fueltr_fuel_st_c42e09_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['date', 'fuel_type', 'fuel_station'], name='fuel_fueltr_date_d8df98_idx'),
        ),
    ]
