# Generated by Django 5.2.1 on 2026-03-13 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_fueltransaction_fuel_fueltr_fuel_ty_7990d5_idx_and_more'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['vehicle', 'driver', 'date'], name='fuel_fueltr_vehicle_adf31c_idx'),
        ),
    ]
