# Generated by Django 5.2.1 on 2025-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_battery_capacity_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate charged per kilometer for this vehicle', max_digits=8, null=True, verbose_name='Rate per KM'),
        ),
    ]
