# Generated by Django 5.2.1 on 2025-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_rate_per_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Firm',
                'verbose_name_plural': 'Firms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='firms',
            field=models.ManyToManyField(help_text='Select one or both firms for this vehicle', related_name='vehicles', to='vehicles.firm'),
        ),
    ]
