# Generated by Django 5.2.1 on 2026-01-08 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owned_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who owns this vehicle (for personal vehicles only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('company', 'Company Vehicle'), ('personal', 'Personal Vehicle (Staff-Owned)')], default='company', help_text='Distinguishes between company and staff personal vehicles', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reimbursement_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reimbursement rate per kilometer for personal vehicles', max_digits=8, null=True, verbose_name='Reimbursement Rate per KM'),
        ),
    ]
