# Generated by Django 5.2.1 on 2026-02-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_department_customuser_department'),
        ('vehicles', '0008_vehicle_owned_by_vehicle_ownership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this vehicle is assigned to (for company vehicles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='accounts.department'),
        ),
    ]
