# Generated by Django 5.2.1 on 2026-02-24 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_permission_is_default_for_company_vehicle_staff_and_more'),
        ('vehicles', '0009_vehicle_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['ownership_type', 'status'], name='vehicles_ve_ownersh_be1823_idx'),
        ),
    ]
