# Generated by Django 5.2.1 on 2025-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_created_at_trip_entry_type_trip_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, help_text='Destination location/address (added when ending trip)', max_length=255, null=True),
        ),
    ]
