# Generated by Django 5.2.1 on 2025-07-08 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_trip_destination'),
        ('vehicles', '0004_vehicle_battery_capacity_kwh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_km', models.DecimalField(decimal_places=2, help_text='Rate per kilometer in Rs (e.g., 16.00)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Whether this rate is currently active', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this consultant rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='The consultant driver', on_delete=django.db.models.deletion.CASCADE, related_name='consultant_rates', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='The vehicle assigned to the consultant', on_delete=django.db.models.deletion.CASCADE, related_name='consultant_rates', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Consultant Rate',
                'verbose_name_plural': 'Consultant Rates',
                'ordering': ['-updated_at'],
                'unique_together': {('driver', 'vehicle', 'status')},
            },
        ),
    ]
