# Generated by Django 5.2.1 on 2025-08-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_soft_delete'),
        ('trips', '0010_consultantrate'),
    ]

    operations = [
    ]
