# Generated by Django 5.2.1 on 2025-12-12 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_merge_0002_trip_soft_delete_0010_consultantrate'),
        ('vehicles', '0007_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'start_time'], name='trips_trip_status_97120d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_trip_driver__692693_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'status'], name='trips_trip_vehicle_b6bc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'end_time'], name='trips_trip_status_a8d451_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_deleted', 'status'], name='trips_trip_is_dele_250f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_time'], name='trips_trip_start_t_aba8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['end_time'], name='trips_trip_end_tim_06844c_idx'),
        ),
    ]
