# Generated by Django 5.2.1 on 2026-01-15 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='gps_end_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude at trip end', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='gps_end_lon',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude at trip end', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='gps_start_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude at trip start', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='gps_start_lon',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude at trip start', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='gps_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Was GPS tracking active for this trip'),
        ),
        migrations.CreateModel(
            name='GPSTrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('interrupted', 'Interrupted'), ('battery_died', 'Battery Died')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0, help_text='Total GPS points collected')),
                ('valid_points', models.IntegerField(default=0, help_text='Points with good accuracy')),
                ('gaps_detected', models.IntegerField(default=0, help_text='Number of signal loss gaps')),
                ('longest_gap_seconds', models.IntegerField(default=0, help_text='Longest gap without GPS')),
                ('gps_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance from GPS (km)', max_digits=10, null=True)),
                ('odometer_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from odometer (km)', max_digits=10, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage difference', max_digits=5, null=True)),
                ('requires_review', models.BooleanField(default=False, help_text='Needs admin review')),
                ('review_reason', models.TextField(blank=True, help_text='Reason for review requirement')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(blank=True, help_text='Admin approval decision', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_reviews', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_session', to='trips.trip')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='GPS Latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='GPS Longitude', max_digits=10)),
                ('accuracy', models.FloatField(help_text='GPS accuracy in meters')),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery percentage at this point', null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='trips.trip')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='trips_tripl_trip_id_25e17b_idx')],
            },
        ),
    ]
