# Generated by Django 5.2.1 on 2026-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_trip_gps_end_lat_trip_gps_end_lon_trip_gps_start_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_odometer_image',
            field=models.ImageField(blank=True, help_text='Photo of odometer at trip end for verification', null=True, upload_to='trips/odometer_images/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_odometer_image',
            field=models.ImageField(blank=True, help_text='Photo of odometer at trip start for verification', null=True, upload_to='trips/odometer_images/'),
        ),
    ]
