# Generated by Django 5.2.1 on 2026-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_trip_end_odometer_image_trip_start_odometer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passenger_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of passengers (applicable for Commercial Staff Bus)', null=True),
        ),
    ]
