# Generated by Django 5.2.1 on 2026-05-12 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_trip_passenger_count'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='approval_action_at',
            field=models.DateTimeField(blank=True, help_text='When the manager approved or rejected the trip.', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='approval_action_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected the trip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_actioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='approval_manager',
            field=models.ForeignKey(blank=True, help_text='Manager (driver.reports_to at submission time) responsible for approving this trip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='approval_remarks',
            field=models.TextField(blank=True, help_text="Manager's remarks for the approval decision."),
        ),
        migrations.AddField(
            model_name='trip',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text="Approval state for personal-vehicle trips. Only 'not_required' or 'approved' trips count for reimbursement.", max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='approval_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the trip was submitted for approval (= end_time at end-trip).', null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['approval_status'], name='trips_trip_approva_ee46af_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['approval_manager', 'approval_status'], name='trips_trip_approva_2fa8e3_idx'),
        ),
    ]
