# Generated by Django 5.2.1 on 2026-05-13 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_approval_action_at_trip_approval_action_by_and_more'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'is_deleted', 'status', 'start_time'], name='trip_driver_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='triplocation',
            index=models.Index(fields=['timestamp'], name='triploc_timestamp_idx'),
        ),
    ]
