# Generated by Django 5.2.1 on 2026-06-29 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_trip_trip_driver_status_time_idx_and_more'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_deleted', 'approval_status', 'approval_submitted_at', 'end_time'], name='trip_approval_list_idx'),
        ),
    ]
