# Generated by Django 5.2.1 on 2026-07-14 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_trip_trip_approval_list_idx'),
        ('vehicles', '0010_vehicle_vehicles_ve_ownersh_be1823_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_deleted', 'approval_status', 'approval_action_at'], name='trip_approval_action_idx'),
        ),
    ]
