# Generated by Django 5.2.1 on 2026-08-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_trip_trip_approval_action_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVisitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_payload', models.JSONField(blank=True, help_text='Raw confirmation payload received from the Appointment System, kept for audit.', null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_visit_token', to='trips.trip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
